# Generated by Django 3.2.2 on 2021-05-13 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today, verbose_name='วันที่')),
                ('OS', models.CharField(choices=[('Window', 'Window'), ('Linux', 'Linux')], default='Window', max_length=10)),
                ('Rom', models.CharField(choices=[('40 GB', '40 GB'), ('80 GB', '80 GB')], default='40 GB', max_length=10)),
                ('Ram', models.CharField(choices=[('4 GB', '4 GB'), ('8 GB', '8 GB')], default='4 GB', max_length=10)),
                ('Servics', models.CharField(choices=[('Web Server', 'Web Server'), ('App Server', 'App Server'), ('Database Server', 'Database Server')], default='Web Server', max_length=20)),
                ('DomainName', models.CharField(default='-', max_length=255, verbose_name='ชื่อโดเมนเนม')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลเซิร์ฟ[ServerData]',
            },
        ),
    ]
