# Generated by Django 3.1.5 on 2021-06-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerData', '0002_auto_20210518_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdata',
            name='Evidence',
            field=models.FileField(blank=True, null=True, upload_to='Evidence/'),
        ),
    ]
